### ISSUE TITLE
Demo website seems KO

### ISSUE THREAD

**Issue by azmeuk** [Pylons/deform#388] opened 2019-08-25 12:57 UTC
There is a lot of links to the demo site in the documentation. All of them seems KO. For instance http://deformdemo.repoze.org/sequence_of_mappings/

**Comment by stevepiercy** [comment] 2019-08-25 13:19
Duplicate of https://github.com/Pylons/deformdemo/issues/58

**Closed by stevepiercy** 2019-08-25 13:19 UTC
