### ISSUE TITLE
Issue with field using readonly template on validation error

### ISSUE THREAD

**Issue by damianrr** [Pylons/deform#163] opened 2013-05-16 16:29 UTC
Hi, i've found that there is a small issue related with validation when some field it's using it's readonly template; the thing is, when you put a readonly template on a field, if the first (and/or subsequest) attempt to send the form for processing doesn't validate, when the form gets re-rendered this readonly field always appears empty. 
Thanks,

**Comment by stevepiercy** [comment] 2020-05-18 04:09
Closing as duplicate of #260

**Closed by stevepiercy** 2020-05-18 04:09 UTC
Labels: sprintable
