### ISSUE TITLE
deform demo domain has bad certificate

### ISSUE THREAD

**Issue by viraptor** [Pylons/deform#408] opened 2020-06-18 10:01 UTC
The link to widget examples on https://docs.pylonsproject.org/projects/deform/en/latest/index.html leads to https://deformdemo.repoze.org/

Unfortunately that endpoint has an invalid certificate on it (hostname doesn't match)

> Firefox does not trust this site because it uses a certificate that is not valid for deformdemo.repoze.org. The certificate is only valid for the following names: pylonsproject.org, static.pylonsproject.org, trypyramid.com, webob.org

**Comment by stevepiercy** [comment] 2020-06-18 10:09
Closing as duplicate of https://github.com/Pylons/deformdemo/issues/58

**Closed by stevepiercy** 2020-06-18 10:09 UTC
