### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by delijati** [Pylons/deform#293] opened 2016-02-10 08:53 UTC
Could someone release the current version

**Comment by stevepiercy** [comment] 2016-02-10 09:17
@delijati Do you mean make a release of the [changes made on the master branch since version 2.0a2](https://github.com/Pylons/deform/blob/master/CHANGES.txt#L1-L46)?

2.0a2 has been released on [PyPI](https://pypi.python.org/pypi/deform). I don't know whether to call that "current".

**Comment by delijati** [comment] 2016-02-10 09:35
The current master.

**Comment by delijati** [comment] 2016-03-31 10:11
Any progress on this?

**Comment by bertjwregeer** [comment] 2016-03-31 12:35
It's unlikely that there will be new releases of deform in the short term. @mcdonc is the only one with permissions to push new versions to the cheeseshop.

You are free to clone this repo, and create a source dist/wheel dist for your own uses/projects.

**Comment by delijati** [comment] 2016-03-31 13:00
And adding some more users to pypi? aka "Role maintenance"

**Comment by stevepiercy** [comment] 2016-03-31 13:11
One could fork the repo and maintain one's own package on PyPI under a new package name. Lots of +/- there, but if a PyPI release is the ultimate goal...

One could also work with the maintainer to determine whether becoming a secondary maintainer on the project is viable.

**Comment by delijati** [comment] 2016-03-31 13:18
I don't see such a problem in "opening" the project it works fine for `collective` e.g. https://github.com/collective/collective.recipe.solrinstance

**Comment by bertjwregeer** [comment] 2016-03-31 13:55
@delijati I've taken over pushing updates to PyPi for a bunch of packages lately for the Pylons Project, I don't mind adding deform. However @mcdonc would have to sign off on it.

Issues that have been expressed is that deform as it is currently released is used by various companies or various projects, and we can't break existing deployments. This means extensive testing needs to be done. HTML forms are rather brittle and there are a bunch of "hacks" to make things sane. Bootstrap updates always bring with them issues for example.

The Pylons Project does not operate like `collective`, this has it's ups and downs.

**Comment by jensens** [comment] 2016-03-31 14:21
Just stumbled over this.

First [semantic versioning](https://semver.org) together with version pinning helps a lot to make these various companies very happy. So if deform uses semantic versioning plus git tags and branches for old stuff nobody will be harmed. 

Second: Well - collective has also its up and downs (but yes, more ups than downs), and collective is about pushing to git repos - not about releasing to pypi. But usually a vital project should have two or more people able to release stuff. We're humans and so something unexpected usually happens at some point. 

To me this two points are much more a sign of quality than a release-wise stalling project - which is in fact a worst case scenario and indicates a dead project.

**Comment by bertjwregeer** [comment] 2016-03-31 16:00
@jensens: Then by all means consider it a dead project, because for all intents and purposes right now it is.

Feel free to fork and continue developing.

**Comment by bertjwregeer** [comment] 2016-03-31 17:02
After thinking about it a little bit. I have no interest in maintaining this project, even from the standpoint of pushing new versions to PyPi, so if you read this @mcdonc I pull that request!

The last release was a little under 3 years ago, and no-one within the Pylons Project is currently actively using deform on any of their projects and is in a position to know what the pitfalls/shortcomings are and what is required to solve them.

If you can convince @mcdonc to make you a maintainer, by all means continue development under the deform name. However at this point my recommendation would be fork the project, rename it, push to PyPi and start building on top of it.

**Comment by tisdall** [comment] 2016-03-31 17:41
@bertjwregeer, Substance D makes use of it.

**Comment by bertjwregeer** [comment] 2016-03-31 18:25
@tisdall which is a project that currently uses the alpha version of deform, and is one of those projects that might break if this is released as-is without regression testing.

SubstanceD is also not something that is currently actively developed/maintained either. It too only has an alpha release on PyPi, from April last year.

**Comment by bertjwregeer** [comment] 2016-03-31 18:37
Discussed this with @mcdonc. At this point I have also added a statement to the README, please fork and I will add a link to the new project.

Thank you.

https://github.com/Pylons/deform/blob/master/README.rst

**Closed by bertjwregeer** 2016-03-31 18:37 UTC

**Comment by piotr-dobrogost** [comment] 2016-03-31 19:33
@bertjwregeer 
Could we know some background leading to abandoning this project by @mcdonc? In the end it seems this is/was rather popular library so I'm wondering if and why people stopped using it?

**Comment by bertjwregeer** [comment] 2016-03-31 19:52
@piotr-dobrogost I can't speak on behalf of @mcdonc but from comments made in the past while working on deform on IRC and other places it's because form handling in HTML is a mess, and doing it right is difficult.

This library is a mix of Python, HTML (bootstrap), Javascript (bootstrap, jquery, and others IIRC), and even the smallest changes affect the whole thing.

Here is what mcdonc said on IRC:

    15th of September, 2015

    13:22:41< mcdonc> Charlie_X: i dont think i'm going to be able to contribute on an issue-by-issue basis in deform issue tracker, sorry, but i can review some fork you create and maybe you can map it back to the issues?
    13:23:58< mcdonc> (i mean contribute in any timeframe that has proven reasonable so far)
    13:33:48< mcdonc> i knew i shouldnt have shown my face in here, now being quoted in issue tracker issues that will surely result in epic handwringing threads
    13:33:53< mcdonc> ;)
    13:34:07< mcdonc> i declare bankruptcy
    13:35:31< x58> mcdonc: link?
    13:35:44< mcdonc> https://github.com/Pylons/deform/issues/279#issuecomment-140499795
    13:35:54< mcdonc> half-joking
    13:35:56< mcdonc> but only half ;)

Since then full bankruptcy has been declared on deform.

There is more discussion here too: https://botbot.me/freenode/pyramid/2015-09-15/?msg=49779534&page=3

Start reading from there, specifically someone, anyone owning the result if they become maintainers, and fixing issues as they come up.
----

People haven't stopped using it per-se, however those of us currently actively working on Pylons Project software don't use it because we have moved to other methods. For example I personally use Angular/React for projects and use JavaScript client side to build/show forms. I use `colander` heavily on the backend for validation, however I don't need a library that renders forms so I have no need for deform.

**Comment by delijati** [comment] 2016-04-01 08:31
@bertjwregeer i think just abandon that project is not the right solution; maybe a transition to a different place something like `pylons-[legacy, whatever]` would be more appropriate.

So that not every developer runs its own solution? I mentioned `collective` earlier and i would propose something like this for `Pylons`. http://collective.github.io/

**Comment by jensens** [comment] 2016-04-01 09:37
I know some people are using deform in Plone in some way. Collective is usually Plone related but contains also packages for a broader audience. It is an complete open space (there only a very soft concept of code-ownership), so maybe a good place for an abandoned project, where there are still people to hug the code. This does not solve the PyPI access issue.

Disclaimer I am not using deform (except in one pet-project, where I tried it out) and I am not planning to contribute. But I can help if it is needed to configure a repository in the collective Github organisation.

**Comment by bertjwregeer** [comment] 2016-04-01 13:43
Feel free to fork the repository, and maintain it where-ever you'd like. PyPi access is the gating issue.

**Comment by delijati** [comment] 2016-04-06 09:27
I would fork it to collective; any name suggestions? `deformer`, `deformed`, `colanderform` ?

**Comment by jensens** [comment] 2016-04-06 09:31
if you plan to use the python namespace deform.* in future:
-> try to get pypi access for deform and keep the name

**Comment by delijati** [comment] 2016-04-06 09:35
@jensens no we need to find a new name @stevepiercy added this to the `README`:

> No new versions or releases to PyPI will be made under the name "deform".

**Comment by jensens** [comment] 2016-04-06 09:37
simply deform2 and keep namespace?

**Comment by delijati** [comment] 2016-06-02 15:08
https://github.com/collective/deform aka `deform2000`.

**Comment by tisdall** [comment] 2016-06-03 12:52
@delijati so it seem deform is now again being actively maintained...  so... 
I guess all that was required was a pycon?  @miohtama, do you have access to pypi too?  The version on pypi is over 2 1/2 years old.

**Comment by miohtama** [comment] 2016-06-03 13:35
I have access to PyPi. Expect new release within one week. There is a lot of things to clean up! 

The new release is "deform" and blessed by Chris.

**Comment by delijati** [comment] 2016-06-03 13:56
oO ohh nice ...
