### ISSUE TITLE
Add custom placeholder support for Checked Password Widget

### ISSUE THREAD

**Issue by KipSigei** [Pylons/deform#351] opened 2017-08-03 07:56 UTC
Add ability to have a custom subject text for  `CheckedPasswordWidget()`

**Comment by stevepiercy** [comment] 2017-08-03 08:36
Possible duplicate of, and partially resolved in https://github.com/Pylons/deform/pull/345, which needs tests and documentation. Contributions to that PR would be welcome.

**Comment by stevepiercy** [comment] 2018-11-10 06:47
Closed by #345

**Closed by stevepiercy** 2018-11-10 06:47 UTC
