### ISSUE TITLE
Select widget with integer values doesn't render with preselected option

### ISSUE THREAD

**Issue by tturkalj** [Pylons/deform#342] opened 2017-04-15 17:12 UTC
I'm using SelectWidget with example values: 
`SelectWidget(values=[("", "-Select option-"), (1, "First option"), (2, "Second option")])`
with` colander.Integer()` schema node.

If I select "Second option" and submit the form with some other required filelds empty, select widget wont render with "Second option" preselected because checking field `cstruct` and `value` fails. `cstruct` is always passed as string and `value` is integer is this case.

I'm using the following jinja2 template for SelectWidget and you can see where checking `value` and `cstruct` happens:

```
<select name="{{ field.name }}"
        id="{{ field.oid }}"
        class="form-control {% if field.error %}form-control-danger{% endif %}"
        {% if field.widget.multiple %}
          multiple
        {% endif %}
>
 {% for value, description in field.widget.values %}
 <option
        {% if value == cstruct %}
        selected="selected"
        {% endif %}
        value="{{ value }}">{{ description }}</option>
{% endfor %}
</select>
```
I can see that SelectWidget has method `get_select_value` and according to documentation it could be used to solve this problem, but it doesn't help at all. I don't event get how it is supposed to work.
For now I have solved this problem by using jinja2 `string` flag on `value`.

**Comment by tisdall** [comment] 2017-04-16 17:05
The values in your `SelectWidget` should always be strings.

**Comment by tturkalj** [comment] 2017-04-25 09:22
Not according to documentation: 

> - a two-tuple (the first value must be of type string, unicode
          or integer, the second value must be string or unicode)
          indicating allowable, displayed values, e.g. ``('jsmith',
          'John Smith')``. The first element in the tuple is the value
          that should be returned when the form is posted. The second
          is the display value;

**Comment by tisdall** [comment] 2017-04-25 12:16
@tturkalj - I have a feeling that while you can provide it as an integer, the value that comes back is a string.  So, when you try to do `value == cstruct` it will fail.  Maybe try something like `str(value) == cstruct`.

**Comment by stevepiercy** [comment] 2020-08-24 12:58
I cannot reproduce this issue. From the deformdemo:

```
    @view_config(renderer="templates/form.pt", name="select")
    @demonstrate("Select Widget")
    def select(self):

        # choices = (
        #     ("", "- Select -"),
        #     ("habanero", "Habanero"),
        #     ("jalapeno", "Jalapeno"),
        #     ("chipotle", "Chipotle"),
        # )
        choices = (
            ("", "- Select -"),
            (1, "one"),
            (2, "two"),
            (3, "three"),
        )

        class Schema(colander.Schema):
            pepper = colander.SchemaNode(
                colander.Integer(),
                widget=deform.widget.SelectWidget(values=choices),
            )
            foo = colander.SchemaNode(
                colander.String(),
            )

        schema = Schema()
        form = deform.Form(schema, buttons=("submit",))

        return self.render_form(form)
```

When I select any value except "- Select -" and submit the form, the correct value is selected.

If you can provide a reproducible example, please reopen this issue. Closing for now.

**Closed by stevepiercy** 2020-08-24 12:58 UTC
