### ISSUE TITLE
Datepicker isn't initialized with hidden column (hidden by DataTables)

### ISSUE THREAD

**Issue by ngoonee** [Pylons/deform#336] opened 2017-02-23 07:53 UTC
I have 8+ columns in my DataTable, and I auto-hide some of them (including one which is of type='date'). While my non-hidden 'date' element gets the appropriate javascript run such that it's callback is registered (and the picker gets brought up on click), the hidden element does not. Unhiding it, unsurprisingly, just shows a normal text input (with type 'date').

DataTables has hooks etc. which I could possibly call, but what function do I need to call to make the previously-hidden date element register it's callback?

**Comment by miohtama** [comment] 2017-02-23 08:14
Thanks @ngoonee. I am not a pickadate.js expert, so I have no idea. Hopefully someone can vouch in here.

**Comment by stevepiercy** [comment] 2020-08-24 12:36
@ngoonee I'm closing this issue because there I don't have a reproducible example. Please feel free to reopen this issue with a reproducible example so we can take a closer look at the issue you describe.

**Closed by stevepiercy** 2020-08-24 12:36 UTC
